//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Col_Attendance {
            get {
                return ResourceManager.GetString("Col_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Col_Away {
            get {
                return ResourceManager.GetString("Col_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Col_Goals {
            get {
                return ResourceManager.GetString("Col_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Col_Home {
            get {
                return ResourceManager.GetString("Col_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Col_Location {
            get {
                return ResourceManager.GetString("Col_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Col_Player {
            get {
                return ResourceManager.GetString("Col_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Col_Score {
            get {
                return ResourceManager.GetString("Col_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        public static string Col_YellowCards {
            get {
                return ResourceManager.GetString("Col_YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Common_Info {
            get {
                return ResourceManager.GetString("Common_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image....
        /// </summary>
        public static string Ctx_ChooseImage {
            get {
                return ResourceManager.GetString("Ctx_ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        public static string Ctx_RemoveImage {
            get {
                return ResourceManager.GetString("Ctx_RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players.
        /// </summary>
        public static string Main_AllPlayers {
            get {
                return ResourceManager.GetString("Main_AllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite players.
        /// </summary>
        public static string Main_Favourites {
            get {
                return ResourceManager.GetString("Main_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string Main_Rankings {
            get {
                return ResourceManager.GetString("Main_Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a team.
        /// </summary>
        public static string Main_SelectTeam {
            get {
                return ResourceManager.GetString("Main_SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Main_Team {
            get {
                return ResourceManager.GetString("Main_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup App.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Match_Opponent {
            get {
                return ResourceManager.GetString("Match_Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Match_OpponentTeam {
            get {
                return ResourceManager.GetString("Match_OpponentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Match_Score {
            get {
                return ResourceManager.GetString("Match_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected team.
        /// </summary>
        public static string Match_SelectedTeam {
            get {
                return ResourceManager.GetString("Match_SelectedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting eleven.
        /// </summary>
        public static string Match_StartingEleven {
            get {
                return ResourceManager.GetString("Match_StartingEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Match_Team {
            get {
                return ResourceManager.GetString("Match_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        public static string Menu_AddToFavourites {
            get {
                return ResourceManager.GetString("Menu_AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favourites.
        /// </summary>
        public static string Menu_RemoveFromFavourites {
            get {
                return ResourceManager.GetString("Menu_RemoveFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit the application?.
        /// </summary>
        public static string Msg_ConfirmExitText {
            get {
                return ResourceManager.GetString("Msg_ConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Msg_ConfirmExitTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to apply these settings?.
        /// </summary>
        public static string Msg_ConfirmSettingsChange {
            get {
                return ResourceManager.GetString("Msg_ConfirmSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confim.
        /// </summary>
        public static string Msg_ConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image.
        /// </summary>
        public static string Msg_ImageChoose {
            get {
                return ResourceManager.GetString("Msg_ImageChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image removed..
        /// </summary>
        public static string Msg_ImageRemoved {
            get {
                return ResourceManager.GetString("Msg_ImageRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select up to 3 favourite players..
        /// </summary>
        public static string Msg_LimitFav {
            get {
                return ResourceManager.GetString("Msg_LimitFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data..
        /// </summary>
        public static string Msg_LoadError {
            get {
                return ResourceManager.GetString("Msg_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading teams: {0}.
        /// </summary>
        public static string Msg_LoadTeamsError {
            get {
                return ResourceManager.GetString("Msg_LoadTeamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a team first..
        /// </summary>
        public static string Msg_NoTeam {
            get {
                return ResourceManager.GetString("Msg_NoTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a team first..
        /// </summary>
        public static string Msg_SelectTeamFirst {
            get {
                return ResourceManager.GetString("Msg_SelectTeamFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings_{0}.pdf.
        /// </summary>
        public static string Pdf_DefaultFileName {
            get {
                return ResourceManager.GetString("Pdf_DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF exported..
        /// </summary>
        public static string Pdf_Exported_Message {
            get {
                return ResourceManager.GetString("Pdf_Exported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Pdf_Exported_Title {
            get {
                return ResourceManager.GetString("Pdf_Exported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export PDF: {0}.
        /// </summary>
        public static string Pdf_ExportFailed_Message {
            get {
                return ResourceManager.GetString("Pdf_ExportFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF export failed.
        /// </summary>
        public static string Pdf_ExportFailed_Title {
            get {
                return ResourceManager.GetString("Pdf_ExportFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files (*.pdf)|*.pdf.
        /// </summary>
        public static string Pdf_Filter {
            get {
                return ResourceManager.GetString("Pdf_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings - {0} - {1}.
        /// </summary>
        public static string Pdf_Title {
            get {
                return ResourceManager.GetString("Pdf_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string Player_Captain {
            get {
                return ResourceManager.GetString("Player_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Player_Defender {
            get {
                return ResourceManager.GetString("Player_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string Player_Favourite {
            get {
                return ResourceManager.GetString("Player_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Player_Forward {
            get {
                return ResourceManager.GetString("Player_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goalie.
        /// </summary>
        public static string Player_Goalie {
            get {
                return ResourceManager.GetString("Player_Goalie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midfield.
        /// </summary>
        public static string Player_Midfield {
            get {
                return ResourceManager.GetString("Player_Midfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string PlayerDetails_Captain {
            get {
                return ResourceManager.GetString("PlayerDetails_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string PlayerDetails_Goals {
            get {
                return ResourceManager.GetString("PlayerDetails_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string PlayerDetails_Number {
            get {
                return ResourceManager.GetString("PlayerDetails_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PlayerDetails_Position {
            get {
                return ResourceManager.GetString("PlayerDetails_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string PlayerDetails_Title {
            get {
                return ResourceManager.GetString("PlayerDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string PlayerDetails_YellowCards {
            get {
                return ResourceManager.GetString("PlayerDetails_YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Rankings_Attendance {
            get {
                return ResourceManager.GetString("Rankings_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Rankings_ExportPdf {
            get {
                return ResourceManager.GetString("Rankings_ExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Rankings_Goals {
            get {
                return ResourceManager.GetString("Rankings_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load rankings: {0}.
        /// </summary>
        public static string Rankings_LoadFailed_Message {
            get {
                return ResourceManager.GetString("Rankings_LoadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings load failed.
        /// </summary>
        public static string Rankings_LoadFailed_Title {
            get {
                return ResourceManager.GetString("Rankings_LoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string Rankings_Title {
            get {
                return ResourceManager.GetString("Rankings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string Rankings_YellowCards {
            get {
                return ResourceManager.GetString("Rankings_YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string Settings_Championship {
            get {
                return ResourceManager.GetString("Settings_Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_En {
            get {
                return ResourceManager.GetString("Settings_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Settings_Hr {
            get {
                return ResourceManager.GetString("Settings_Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Settings_Men {
            get {
                return ResourceManager.GetString("Settings_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will apply after restart.
        /// </summary>
        public static string Settings_SaveRestart {
            get {
                return ResourceManager.GetString("Settings_SaveRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window mode.
        /// </summary>
        public static string Settings_WindowMode {
            get {
                return ResourceManager.GetString("Settings_WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Settings_Women {
            get {
                return ResourceManager.GetString("Settings_Women", resourceCulture);
            }
        }
    }
}
