//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Main_Info {
            get {
                return ResourceManager.GetString("Main_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent:.
        /// </summary>
        public static string Main_Opponent {
            get {
                return ResourceManager.GetString("Main_Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Main_OpponentTeam {
            get {
                return ResourceManager.GetString("Main_OpponentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Main_Players {
            get {
                return ResourceManager.GetString("Main_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected team.
        /// </summary>
        public static string Main_SelectedTeam {
            get {
                return ResourceManager.GetString("Main_SelectedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting eleven.
        /// </summary>
        public static string Main_StartingEleven {
            get {
                return ResourceManager.GetString("Main_StartingEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team:.
        /// </summary>
        public static string Main_Team {
            get {
                return ResourceManager.GetString("Main_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF.
        /// </summary>
        public static string Main_TitlePrefix {
            get {
                return ResourceManager.GetString("Main_TitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        public static string Menu_AddToFavourites {
            get {
                return ResourceManager.GetString("Menu_AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_RemoveFromFavourites.
        /// </summary>
        public static string Menu_RemoveFromFavourites {
            get {
                return ResourceManager.GetString("Menu_RemoveFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit the application?.
        /// </summary>
        public static string Msg_ConfirmExitText {
            get {
                return ResourceManager.GetString("Msg_ConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Msg_ConfirmExitTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to apply these settings?.
        /// </summary>
        public static string Msg_ConfirmSettingsChange {
            get {
                return ResourceManager.GetString("Msg_ConfirmSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Msg_ConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load match failed.
        /// </summary>
        public static string Msg_LoadMatchFailed {
            get {
                return ResourceManager.GetString("Msg_LoadMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load opponents failed.
        /// </summary>
        public static string Msg_LoadOpponentsFailed {
            get {
                return ResourceManager.GetString("Msg_LoadOpponentsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load players failed.
        /// </summary>
        public static string Msg_LoadPlayersFailed {
            get {
                return ResourceManager.GetString("Msg_LoadPlayersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load teams failed.
        /// </summary>
        public static string Msg_LoadTeamsFailed {
            get {
                return ResourceManager.GetString("Msg_LoadTeamsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found..
        /// </summary>
        public static string Msg_NoMatchFound {
            get {
                return ResourceManager.GetString("Msg_NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain: No.
        /// </summary>
        public static string PlayerInfo_CaptainNo {
            get {
                return ResourceManager.GetString("PlayerInfo_CaptainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain: Yes.
        /// </summary>
        public static string PlayerInfo_CaptainYes {
            get {
                return ResourceManager.GetString("PlayerInfo_CaptainYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals (this match): {0}.
        /// </summary>
        public static string PlayerInfo_GoalsThisMatchFormat {
            get {
                return ResourceManager.GetString("PlayerInfo_GoalsThisMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} • {1}.
        /// </summary>
        public static string PlayerInfo_MetaFormat {
            get {
                return ResourceManager.GetString("PlayerInfo_MetaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player info.
        /// </summary>
        public static string PlayerInfo_Title {
            get {
                return ResourceManager.GetString("PlayerInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards (this match): {0}.
        /// </summary>
        public static string PlayerInfo_YellowThisMatchFormat {
            get {
                return ResourceManager.GetString("PlayerInfo_YellowThisMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string Settings_Championship {
            get {
                return ResourceManager.GetString("Settings_Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_En {
            get {
                return ResourceManager.GetString("Settings_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Settings_Fullscreen {
            get {
                return ResourceManager.GetString("Settings_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Settings_Hr {
            get {
                return ResourceManager.GetString("Settings_Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Settings_Men {
            get {
                return ResourceManager.GetString("Settings_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Settings_Resolution {
            get {
                return ResourceManager.GetString("Settings_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Settings_Women {
            get {
                return ResourceManager.GetString("Settings_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team info failed.
        /// </summary>
        public static string TeamInfo_FailedTitle {
            get {
                return ResourceManager.GetString("TeamInfo_FailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference: [{0}].
        /// </summary>
        public static string TeamInfo_GoalDiffFormat {
            get {
                return ResourceManager.GetString("TeamInfo_GoalDiffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for / against: [{0} / {1}].
        /// </summary>
        public static string TeamInfo_GoalsForAgainstFormat {
            get {
                return ResourceManager.GetString("TeamInfo_GoalsForAgainstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string TeamInfo_NoData {
            get {
                return ResourceManager.GetString("TeamInfo_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played: [{0}].
        /// </summary>
        public static string TeamInfo_PlayedFormat {
            get {
                return ResourceManager.GetString("TeamInfo_PlayedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team info.
        /// </summary>
        public static string TeamInfo_Title {
            get {
                return ResourceManager.GetString("TeamInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins / Draws / Losses: [{0} / {1} / {2}].
        /// </summary>
        public static string TeamInfo_WdlFormat {
            get {
                return ResourceManager.GetString("TeamInfo_WdlFormat", resourceCulture);
            }
        }
    }
}
